apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: web 
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        server {
            listen 80;
            server_name dev-eks-lb-nginx-982130635.ap-northeast-2.elb.amazonaws.com;

            location / {
                proxy_pass http://streamlit-service:8501;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
            }

            location /_stcore/stream {
                    proxy_pass http://streamlit-service:8501/_stcore/stream;
                    proxy_http_version 1.1;
                    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                    proxy_set_header Host $host;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection "upgrade";
                    proxy_read_timeout 86400;
            }

            # Static files (CSS, JS, etc.) support
            location /static {
                proxy_pass http://streamlit-service:8501/static;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /component {
                proxy_pass http://streamlit-service:8501/component;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /status {
                stub_status on;
                allow all;
            }
        }
    }
